# if this is not set, clipbud will show itself at every clipboard change
hotkey: "CMD+CTRL+C"

# light, dark or system (default to system if empty)
theme: dark

# you can add your API keys here, or set them as environment variables
keys:
  OPENAI_API_KEY: "sk-proj-1234567890"
  ANTHROPIC_API_KEY: "sk-ant-api03-..."

# default to horizontal wrap if not set, set to none to disable wrapping
# and show all buttons by resizing the window vertically
wrap_buttons: horizontal

# here you'll define the actions that will be available in the UI
actions:
  - label: "Fix"
    prompt: "Fix typos and grammar of the following text, but keep the original meaning and structure:"
    key: "T" # optional shortcut key
    model: "gpt-4o"
    provider: "openai"

  - label: "Summarize"
    prompt: "Summarize the following text in less than 200 words:"
    key: "S"
    model: "gpt-4o"
    provider: "openai"
    # by default responses are pasted to the clipboard, set this to false to disable
    paste: false

  - label: "Formal"
    prompt: "Make the following text more formal:"
    key: "F"
    model: "gpt-4o"
    provider: "openai"

  - label: "ELI5"
    prompt: "Explain the following text in a way that is easy to understand for a 5 year old:"
    key: "E"
    model: "gpt-4o"
    provider: "openai"
    # only show response without pasting to the clipboard
    paste: false