hotkey: "CMD+CTRL+C"

actions:
  - label: "Typos"
    prompt: "Fix typos and grammar of the following text, but keep the original meaning and structure, only return the fixed text and nothing else:"
    key: "T"
    model: "gpt-4o"
    provider: "openai"

  - label: "Summarize"
    prompt: "Summarize the following text in less than 200 words, only return the summary and nothing else:"
    key: "S"
    model: "gpt-4o"
    provider: "openai"

  - label: "Friendly"
    prompt: "Make the following text more friendly, only return the friendly text and nothing else:"
    key: "F"
    model: "gpt-4o"
    provider: "openai"

  - label: "ELI5"
    prompt: "Explain the following text in a way that is easy to understand for a 5 year old, only return the explanation and nothing else:"
    key: "E"
    model: "gpt-4o"
    provider: "openai"